name: Retention
description: Request for updating retention period
title: "(retention) <title>"
labels: retention
projects:
  - SigNoz/21
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the customer or the associated deployment
    validations:
      required: true
  - type: input
    id: reference
    attributes:
      label: Reference
      description: Link to the intercom, slack thread or email thread for the support request
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Activated
      description: Is the license ACTIVATED
      options:
        - label: something
          required: true
  - type: input
    id: logs
    attributes:
      label: Retention period for Logs
      description: Please provide retention period for logs
    validations:
      required: true
  - type: input
    id: logs-pricing
    attributes:
      label: Pricing for the new retention for logs
      description: Please provide updated pricing for logs
    validations:
      required: true
  - type: input
    id: traces
    attributes:
      label: Retention period for Traces
      description: Please provide retention period for traces
    validations:
      required: true
  - type: input
    id: traces-pricing
    attributes:
      label: Pricing for the new retention for traces
      description: Please provide updated pricing for traces
    validations:
      required: true
  - type: input
    id: metrics
    attributes:
      label: Retention period for Metrics
      description: Please provide retention period for metrics
    validations:
      required: true
  - type: input
    id: metrics-pricing
    attributes:
      label: Pricing for the new retention for metrics
      description: Please provide updated pricing for metrics
    validations:
      required: true
